version: '3.6'
services:
  db:
    image: "postgres:10"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - "TZ=Japan"
  # spring:
  #   <<: *app_base
  #   command: ["bundle", "exec", "spring", "server"]
  #   ports: []
  #   tty: false
  #   stdin_open: false

  # data:
  #   image: "busybox"
  #   volumes:
  #     - "db:/var/lib/postgresql/data"
  #     - "bundle:/usr/local/bundle"
  # mailcatcher:
  #   image: "pocari/mailcatcher"
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"
  # chrome:
  #   image: selenium/standalone-chrome-debug:3.9.1-actinium
  #   ports:
  #     - 4444:4444
  #     - 5900:5900

# volumes:
#   db:
#     driver: local
  # bundle:
  #   driver: local
