#!/usr/bin/env bash
cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm app rails new . --force --database=postgresql --skip-bundle --skip-git --skip-test

sed -i '' "s/# gem \'mini_racer\'/gem \'mini_racer\'/g" Gemfile

docker-compose run --rm app bundle update
docker-compose run --rm app bundle install

cp -f template/database.yml config/database.yml

docker-compose run --rm app bundle exec spring binstub --all

rm -rf .git
git init
git add .
git commit -m "init" -q
