#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm rails rails new . --force --database=postgresql --skip-bundle --skip-git --skip-test && bundle update

sed -i '' "s/# gem \'therubyracer\'/gem \'therubyracer\'/g" Gemfile

cp -f template/database.yml config/database.yml

rm -rf .git
git init
git add .
git commit -m "init"

docker-compose run --rm rails bundle exec spring binstub --all
