#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

# docker-compose run --rm rails rails new . --force --database=postgresql --skip-bundle --skip-git --skip-test -m https://gist.githubusercontent.com/masashi-fuji/26e4f31397e39193dbf002a8b714ea38/raw/slim-rails.rb

docker-compose run --rm rails rails new . --force --database=postgresql --skip-bundle --skip-git --skip-test

sed -i '' "s/# gem \'mini_racer\'/gem \'mini_racer\'/g" Gemfile

docker-compose run --rm rails bundle update
docker-compose run --rm rails bundle install

#cp -f template/database.yml config/database.yml

docker-compose run --rm rails bundle exec spring binstub --all
#docker-compose run --rm rails erb2slim app/views app/views -d

# rm -rf .git
# git init
# git add .
# git commit -m "init" -q
